name: dev
root: ./

windows:
  - nvim: nvim
  - git:
      layout: even-vertical
      panes:
        - bin/rails console
        - #
  - server: 
      layout: even-horizontal
      panes:
        - bin/rails server -b 0.0.0.0
        - cd frontend/ && npm start
